// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWNUXLU8cxJTNqdbnFAWrhqqU97rcGA50',
    appId: '1:1063791437321:web:353a6b782fd2caecc63ad8',
    messagingSenderId: '1063791437321',
    projectId: 'flutter-application-gema',
    authDomain: 'flutter-application-gema.firebaseapp.com',
    storageBucket: 'flutter-application-gema.firebasestorage.app',
    measurementId: 'G-6PNN9MXSSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSXdQ0cF-Vuv0W_b3JlxTOm-GFsEkHhcw',
    appId: '1:1063791437321:android:a978fa0cf8a29694c63ad8',
    messagingSenderId: '1063791437321',
    projectId: 'flutter-application-gema',
    storageBucket: 'flutter-application-gema.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWNUXLU8cxJTNqdbnFAWrhqqU97rcGA50',
    appId: '1:1063791437321:web:d1b32d9767c8d87fc63ad8',
    messagingSenderId: '1063791437321',
    projectId: 'flutter-application-gema',
    authDomain: 'flutter-application-gema.firebaseapp.com',
    storageBucket: 'flutter-application-gema.firebasestorage.app',
    measurementId: 'G-XZW1J2DQJX',
  );

}